### ISSUE TITLE
ExtensionElements

### ISSUE THREAD

**Issue by roshanmedatwal** [valb3r/flowable-bpmn-intellij-plugin#239]
We are looking at migration of workflows Activiti from Eclipse to Flowable in IntelliJ.
We notice that the IntelliJ plugin did not have form properties in the start event. Most of our workflow variables are declared at the startevent and when we migrate to Flowable in IntelliJ we receive a null pointer error.

1. Go to a new Flowable diagram
2. Right click and create a Start Event
3. Under the BPM Flow Diagram only visible options are ID, Name and Documentation. Eclipse Flowable plugin also contains Form properties.
4. Please let us know how this situation can be handled.

**IntelliJ version:
 - Edition: Ultimate
 - Version: 2021.1.1

** Flowable Plugin Version:
- Version: 0.4.6.2

**Comment by valb3r** [comment]
@roshanmedatwal
1. You are going to use Flowable BPMN instead of Activiti BPMN?
2. It is of course doable. Ideally, such feature requests should be accompanied with example BPMN files, so I can see exactly which fields are necessary to be displayed in UI. Otherwise, I need first to create BPMN myself guess if it suits your request, and implement a feature. I would really appreciate if you provide example BPMN file where those form properties are available.

**Comment by roshanmedatwal** [comment]
1. We will need a flowable bpmn. We already have activiti workflows created as part of eclipse. We need to migrate them to flowable intellij. 
2. We will try to create some examples and provide it here.
